/******** MUSIC.H*******/   
#define  T  22118400/12/2  //T=Fosc/12/2=基本頻率

/*---第0八度音階---*/   
#define  DO1     T/65
#define  DO_1    T/69  //DO1# 
#define  RE1     T/73
#define  RE_1    T/78  //RE1# 
#define  MI1     T/82
#define  FA1     T/87
#define  FA_1    T/93  //FA1# 
#define  SO1     T/98
#define  SO_1    T/104 //SO1# 
#define  LA1     T/110
#define  LA_1    T/116 //LA1# 
#define  SI1     T/123
/*---第1八度音階---*/   
#define  DO2     T/131
#define  DO_2    T/139 //DO2# 
#define  RE2     T/147
#define  RE_2    T/156 //RE2# 
#define  MI2     T/165
#define  FA2     T/175
#define  FA_2    T/185 //FA2# 
#define  SO2     T/196
#define  SO_2    T/208 //SO2# 
#define  LA2     T/220
#define  LA_2    T/233 //LA2# 
#define  SI2     T/247
/*---第2八度音階---*/   
#define  DO3     T/262
#define  DO_3    T/277 //DO3# 
#define  RE3     T/294
#define  RE_3    T/311 //RE3# 
#define  MI3     T/330
#define  FA3     T/349
#define  FA_3    T/370 //FA3# 
#define  SO3     T/392
#define  SO_3    T/415 //SO3# 
#define  LA3     T/440
#define  LA_3    T/466 //LA3# 
#define  SI3     T/494
/*---第3八度音階---*/ 
#define  DO4     T/523
#define  DO_4    T/554 //DO4# 
#define  RE4     T/587
#define  RE_4    T/622 //RE4# 
#define  MI4     T/659
#define  FA4     T/698
#define  FA_4    T/740 //FA4# 
#define  SO4     T/784
#define  SO_4    T/831 //SO4# 
#define  LA4     T/880
#define  LA_4    T/932 //LA4#  
#define  SI4     T/988
/*---第4八度音階---*/  
#define  DO5    T/1046
#define  DO_5   T/1109 //DO5#     
#define  RE5    T/1175
#define  RE_5   T/1245 //RE5#   
#define  MI5    T/1318
#define  FA5    T/1397
#define  FA_5   T/1480 //FA5#   
#define  SO5    T/1568
#define  SO_5   T/1661 //SO5#   
#define  LA5    T/1760
#define  LA_5   T/1865 //LA5# 
#define  SI5    T/1976
/*---第5八度音階---*/   
#define  DO6    T/2093
#define  DO_6   T/2217 //DO6# 
#define  RE6    T/2349
#define  RE_6   T/2489 //RE6# 
#define  MI6    T/2637
#define  FA6    T/2794
#define  FA_6   T/2960 //FA6# 
#define  SO6    T/3136
#define  SO_6   T/3322 //SO6# 
#define  LA6    T/3520
#define  LA_6   T/3729 //LA6# 
#define  SI6    T/3951
/*---第6八度音階---*/ 
#define  DO7    T/4086
#define  DO_7   T/4435 //DO7# 
#define  RE7    T/4699
#define  RE_7   T/4978 //RE7# 
#define  MI7    T/5274
#define  FA7    T/5587
#define  FA_7   T/5919 //FA7# 
#define  SO7    T/6271
#define  SO_7   T/6645 //SO7# 
#define  LA7    T/7040
#define  LA_7   T/7459 //LA7# 
#define  SI7    T/7902


